# Lista de exercícios sobre libraria Numpy

<br/>**Disciplina**: Introdução a Redes Neurais Profundas 2018/1
<br/>**Professor**: Jorge Leonid Aching Samatelo

**Aluno**: Marcos A. Spalenza

## Tabela de conteúdos
1. [Exercícios sobre Numpy](#ExerNumpy)
1. [Exercícios de Programação](#ExerProgramacao)

## Exercícios sobre Numpy <a name="ExerString"></a>

## Exe. 1
Crie uma matriz nxn com valores 1,2,...,n-1 logo abaixo da diagonal.

Exemplo: Considerando n = 4.
```
A = [0 0 0 0 0]
    [1 0 0 0 0]
    [0 2 0 0 0]
    [0 0 3 0 0]
    [0 0 0 4 0]
```

In [195]:
import numpy as np

n = 4
mat = np.zeros((n+1,n+1))

pos = [(i1, i2) for i1 in range(np.shape(mat)[0]) for i2 in range(np.shape(mat)[1])  if i1-1 == i2]

for p1, p2 in pos:
  mat[p1, p2] = p1

print(mat)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## Exe. 2
Crie uma matriz nxn com 1 na borda e 0 dentro.

Exemplo: Considerando n = 10.
```
Z = [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
```

In [196]:
import numpy as np

n = 10

mat = np.zeros((n,n))

mat[0, :]  = np.ones(n)
mat[:, 0] = np.ones(n)
mat[-1, :] = np.ones(n)
mat[:, -1] = np.ones(n)

print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Exe. 3
Crie uma matriz nxn, com n par, e preenchê-lo com um padrão de xadrez.

Exemplo: Considerando n = 8.
```
Z = [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
```

In [197]:
import numpy as np

n = 9

mat = np.zeros((n,n))

for ind, val in np.ndenumerate(mat):
    i, j = ind
    if i % 2 != 0 and j % 2 == 0:
        mat[i, j] = 1
    elif i % 2 == 0 and j % 2 != 0:
        mat[i, j] = 1

print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0.]]


## Exe. 4
Criar um vetor de tamanho 10 inicializada com valores entre $<0,1>$.

Exemplo:
```
Z= [0.091 0.181 0.272 0.363 0.454 0.545 0.636 0.727 0.818 0.909]
```

In [198]:
import numpy as np

arr = np.random.rand(10)

print(arr)

[0.00493124 0.68814509 0.15155579 0.55918507 0.65639088 0.64140309
 0.72668765 0.28712461 0.3369292  0.8201086 ]


## Exe. 5
Dado um array, negar todos os elementos que estão entre 3 e 8.

Exemplo:
```
Zorg =  [ 0  1  2  3  4  5  6  7  8  9 10]
Ztrf =  [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
```

In [199]:
import numpy as np
negate = ((3, 8))

z_org = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
z_trf = np.array(z_org)
z_trf[np.logical_and(z_trf>3, z_trf<=8)] *= -1
print(z_trf)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## Exe. 6
Extraia a parte inteira de uma array de números aleatórios entre  1.0 e 10.0 usando 5 métodos diferentes.

Exemplo (para um caso):
```
Z  =  [7.497 6.573 9.946 2.645 2.501 8.911 4.301 9.643 4.361 4.128]
Z1 =  [ 7.  6.  9.  2.  2.  8.  4.  9.  4.  4.]
```

In [200]:
import numpy as np
n = 10
z = np.random.uniform(1.0, 10.0, size=n)

print(z)

# modo1
print(z.astype(int))

# modo2
print(np.trunc(z))

# modo 3
print(np.floor(z))

# modo 4
print(np.divmod(z, 1)[0])

# modo 5
print(np.modf(z)[1])

[8.46885266 9.22710485 7.9773686  3.67981562 4.88907834 1.75860873
 9.04189458 2.5877862  9.36001627 5.98292564]
[8 9 7 3 4 1 9 2 9 5]
[8. 9. 7. 3. 4. 1. 9. 2. 9. 5.]
[8. 9. 7. 3. 4. 1. 9. 2. 9. 5.]
[8. 9. 7. 3. 4. 1. 9. 2. 9. 5.]
[8. 9. 7. 3. 4. 1. 9. 2. 9. 5.]


## Exe. 7
Considere dois arrays $A$ e $B$ aleatórios inicializados com valores aleatorios inteiros, verifique se eles são iguais.

Exemplo:
```
A =  [2 2 0 2 1]
B =  [1 0 2 3 3]
False
```

In [201]:
import numpy as np

n = 5
max_, min_ = (0, 10)
a = np.random.randint(max_, min_, size=n)
b = np.random.randint(max_, min_, size=n)

print(a)
print(b)
print(False not in np.equal(a,b))

[8 5 5 2 7]
[3 3 6 0 0]
False


## Exe. 8
Considere uma matriz aleatória de 10x2 que representa coordenadas cartesianas, converta-as em coordenadas polares.

In [210]:

import numpy as np

def polar_coord(x, y):
    r = (x ** 2 + y ** 2) ** .5
    if y == 0:
        degree_ = 180 if x < 0 else 0
    elif x == 0:
        degree_ = 90 if y > 0 else 270
    else:
      degree_ = np.degrees(np.arctan(float(y) / x))
    return round(r,3), round(degree_,3)

n = (10, 2)
max_, min_ = (-10, 10)

coord = np.array(np.random.randint(max_, min_, size=n))

print(coord)
print([polar_coord(round(x, 3), round(y, 3)) for x, y in coord])

[[  4  -6]
 [ -2   6]
 [  1   0]
 [  7   9]
 [ -1  -5]
 [ -4  -6]
 [ -3  -4]
 [  2 -10]
 [  8   8]
 [-10   1]]
[(7.211, -56.31), (6.325, -71.565), (1.0, 0), (11.402, 52.125), (5.099, 78.69), (7.211, 56.31), (5.0, 53.13), (10.198, -78.69), (11.314, 45.0), (10.05, -5.711)]


## Exe. 9
Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor.

Exemplo:
```
Zorg =  [1 2 3 4 5]
Z000 =  [ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]
```

In [203]:
import numpy as np

z_org = np.array([1, 2, 3, 4, 5])

for i in reversed(range(z_org.shape[0])):
    if i != 0:
        z_org = np.insert(z_org, i, np.zeros(3))
print(z_org)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


## Exe. 10
Encontre o valor mais próximo de um dado valor em um array.

Exemplo:
```
Z =  [0.198 0.825 0.057 0.695 0.0333 0.793 0.526 0.547 0.787  0.656]
valor =  0.5
valor proximo em Z = 0.526929001754
```

In [204]:
import numpy as np

value = 0.5

#arr = np.random.rand(10)

arr = np.array([0.198, 0.825, 0.057, 0.695, 0.0333, 0.793, 0.526, 0.547, 0.787, 0.656])

print(arr)
print("Valor = "+str(value))
print("Valor mais próximo de "+str(value)+" é "+str(arr[np.abs(arr-value).argmin()]))

[0.198  0.825  0.057  0.695  0.0333 0.793  0.526  0.547  0.787  0.656 ]
Valor = 0.5
Valor mais próximo de 0.5 é 0.526


## Exercícios de Programação <a name="ExerProgramacao"></a>

## Exe. 1

Como encontrar o valor mais freqüente em um array?

Exemplo:
```
Z = [8 1 8 1 9 6 2 7 0 1 7 1 6 7 9 6 0 2 1 9 8 9 0 6 9 7 1 4 2 8 1 6 4 6 1 3 5 0 1 1 5 5 0 9 4 9 9 1 1 2]
ValMoreFreq = 1
```

In [205]:
import numpy as np

a = [8, 1, 8, 1, 9, 6, 2, 7, 0, 1, 7, 1, 6, 7, 9, 6, 0, 2, 1, 9, 8, 9, 0, 6, 9, 7, 1, 4, 2, 8, 1, 6, 4, 6, 1, 3, 5, 0, 1, 1, 5, 5, 0, 9, 4, 9, 9, 1, 1, 2]

cnt = np.bincount(a)

print("ValMoreFreq = "+str(np.argmax(cnt)))

ValMoreFreq = 1


## Exe. 2

Considere duas matrizes A e B de forma (8,3) e (2,2). Como encontrar as linhas de A que contêm elementos de cada linha de B independentemente da ordem dos elementos em B? 

Exemplo:
```
A = [[2 1 4]
     [3 2 2]
     [3 4 1]
     [3 0 0]
     [4 3 4]
     [0 0 1]
     [2 1 4]
     [0 3 1]]
B = [[1 4]
     [2 4]]
rows = [0 1 2 4 6]
```

In [206]:
import numpy as np

a = np.array([[2, 1, 4], [3, 2, 2], [3, 4, 1], [3, 0, 0], [4, 3, 4], [0, 0, 1], [2, 1, 4], [0, 3, 1]])
b = np.array([[1, 4], [2, 4]])

print([enum for enum, a_ in enumerate(a) if np.shape(np.where(np.isin(a_, b)))[1] >= 2])


[0, 1, 2, 4, 6]


## Exe. 3
Dado um array bidimensional, como extrair linhas unicas?

Exemplo:
```
Z = [[0 0 1]
     [1 0 0]
     [1 1 0]
     [1 1 1]
     [0 1 1]
     [1 1 0]]
Zu = [[0 0 1]
      [0 1 1]
      [1 0 0]
      [1 1 0]
      [1 1 1]]
```

In [207]:
z = [[0, 0, 1], [1, 0, 0], [1, 1, 0], [1, 1, 1], [0, 1, 1], [1, 1, 0]]

print(np.unique(z, axis=0))

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


## Exe. 4
Converter um vetor de inteiros em uma matriz que seja sua representação binária.

Exemplo:
```
I = [0 1 2 3 15 16 32 64 128]
B = [[0 0 0 0 0 0 0 0]
     [0 0 0 0 0 0 0 1]
     [0 0 0 0 0 0 1 0]
     [0 0 0 0 0 0 1 1]
     [0 0 0 0 1 1 1 1]
     [0 0 0 1 0 0 0 0]
     [0 0 1 0 0 0 0 0]
     [0 1 0 0 0 0 0 0]
     [1 0 0 0 0 0 0 0]]
```

In [208]:
import numpy as np

i = [0, 1, 2, 3, 15, 16, 32, 64, 128]

values = [list(np.binary_repr(i_)) for i_ in i]

mat = np.zeros((len(i), len(max(values, key=len))))

for line in range(np.shape(mat)[0]):
    item = values[line]
    for col, val in enumerate(reversed(item)):
        mat[line, -1-col] = val
print(mat)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]


## Exe. 5
Considerando uma matriz 10x3, extraia linhas com valores desiguais (por exemplo, [2,2,3])

Exemplo:
```
Z = [[2 2 0]
     [1 1 3]
     [4 3 3]
     [1 0 1]
     [2 2 2]
     [2 3 3]
     [1 1 0]
     [0 2 0]
     [4 4 0]
     [4 2 3]]
Zd = [[2 2 0]
      [1 1 3]
      [4 3 3]
      [1 0 1]
      [2 3 3]
      [1 1 0]
      [0 2 0]
      [4 4 0]
      [4 2 3]]
```

In [209]:
import numpy as np

arr = [[2, 2, 0], [1, 1, 3], [4, 3, 3], [1, 0, 1], [2, 2, 2], [2, 3, 3], [1, 1, 0], [0, 2, 0], [4, 4, 0], [4, 2, 3]]

print([a for a in arr if len(np.unique(a)) > 1])

[[2, 2, 0], [1, 1, 3], [4, 3, 3], [1, 0, 1], [2, 3, 3], [1, 1, 0], [0, 2, 0], [4, 4, 0], [4, 2, 3]]
